### ISSUE TITLE
Implement a Task Register

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#107]
Implement a task register

![image](https://user-images.githubusercontent.com/25123762/53391113-66966f00-39a6-11e9-997c-711cca478861.png)

- [x] The register will have a toolbar
- [x] The toolbar will have a hamburger menu icon that when clicked will open the landing page for one to select campaign
- [x] The toll bar title will be centered and text is Reveal
- [x] The toolbar on the right has an icon to open the map view

- [x] Below the toolbar the intervention type will be displayed

- [x] The register will display the number of structures within the location buffer and also the total structures

- [x] Structures will be ordered by proximity to user

- [x] Operational area tasks will be first in the list

- [x] Each row in the register will represent a task

- [x] The labels and icon will be custom depending on the target for task

- [x] The first column of the row will have details of the target for the task e.g the structures details and distance, 

- [x] The second column will have a button that when clicked will launch a form for the task

**Comment by githengi** [comment]
@craigappl will all tasks be shown even those that have been completed

**Comment by githengi** [comment]
@craigappl @rowo if we all displaying all tasks, can we page then or the user scrolls to the bottom? 

There are some operational areas with 500+ structures.

**Comment by githengi** [comment]
@craigappl I am refreshing the register whenever the user moves by configurable number of meters. Should this be configuration moved to a server configuration

**Comment by rowo** [comment]
I think @craigappl should review my below answers, but here's what I think:

- I don't think completed tasks should disappear. Though I'm not sure what to do about the operational area-wide task like BCC. That will always be "in the area" since it applies to the whole operational area, but you don't want it taking up the first row all of the time. We could treat BCC special and move it to the bottom of the list if it's done...
- "2 structures within 20m" - The 20m part would make sense for the outer radius (blue circle). "User configurable" means "determined by implementer" and not the individual user, correct?
- Re: Disabling distance. This list is ordered by distance from user. I guess distance can just not appear and whatever point is easy to calculate (center of operational area?) would be the reference point for the order of the list. To keep it simple. If there's another simpler way to do it, please mention.
- Re: pagination. I don't think we have to prioritize this list view at all — meaning, I think we can cut it off at a reasonable number like 30. If we are using the mSpray model, the only time I see someone actually scroll through this list is if they are looking for someone specific in the vicinity they are in.

**Comment by githengi** [comment]
> * "2 structures within 20m" - The 20m part would make sense for the outer radius (blue circle). "User configurable" means "determined by implementer" and not the individual user, correct?

Yes

> Re: Disabling distance:

 That makes a good idea, if location services are disabled, we calculate distance from center of operational area. We could amend the message to indicate the distance is from center of operational area and not from user.

**Comment by githengi** [comment]
@rowo in task register when clicking a task that has previous data collected it open the some form of details screen like on the Map view e.g
[IRS](https://marvelapp.com/6b2b86b/screen/53790460)
[FI](https://marvelapp.com/6b2b86b/screen/53338045)

**Comment by githengi** [comment]
If location services are disabled then display distance from center of operational area.
