### ISSUE TITLE
The occupation field only shows when one types the age instead o selecting the calendar

### ISSUE THREAD

**Issue by Naima-Bashir** [opensrp/opensrp-client-reveal#1357]
Login to the thai apk(the latest)
Register a new residential structure
Fill in the family details 
Observe the age part:
when one selects the age via the calendar, the occupation field is  hidden
When one manually types the age, the occupation field is shown. 
See images below
![WhatsApp Image 2021-04-12 at 07 57 11](https://user-images.githubusercontent.com/61143692/114367737-6b6a0d00-9b85-11eb-84de-5d5bfe43a33b.jpeg)
![WhatsApp Image 2021-04-12 at 07 56 36](https://user-images.githubusercontent.com/61143692/114367744-6c9b3a00-9b85-11eb-8884-341cab4da828.jpeg)

**Comment by LZRS** [comment]
Setting the forms to have `family-member-relevance.yml`  rule of
 `step1_age >= 18 || helper.formatDate(step1_dob,"y") >= 18`, for both date-of-birth and age fields, does not seem to work...

**Comment by Rkareko** [comment]
@LZRS cc @Naima-Bashir The fix for this will be done via the form configuratoin feature

**Comment by LZRS** [comment]
In the `family-member-relevance.yml` for `step1_occupation` form `condition` instead of `"step1_age >= 18"`, use `"step1_dob_unknown.contains('dob_unknown') ? (step1_age >= 18) : (helper.formatDate(step1_dob, 'y') >= 18)"`

In the `family-register-relevance.yml` for `step2_occupation` form `condition` instead of `"step2_age >= 18"`, use `"step2_dob_unknown.contains('dob_unknown') ? (step2_age >= 18) : (helper.formatDate(step2_dob, 'y') >= 18)"`

**Comment by madrinekariuki** [comment]
for a user above 18 years when you select from the calendar or input their age, we are able to see the occupation field.
see below screenshot. 
![image](https://user-images.githubusercontent.com/84722169/123649148-35f2c880-d832-11eb-8d00-8205e0557d17.png)
