### ISSUE TITLE
Failing Offline Map for Thailand

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-reveal#1469]
Thailand has reported that on the production instance, the maps downloaded offline are failing about 24hours from when the users go offline. At the 24hr mark the map is fully black and unusable for field activities. See the video provided [here](https://dsme.slack.com/archives/GRVF5Q5T7/p1625566164017800). 

The video is based on the following:
- Plan Name: A1 - ห้วยผาก (7003070604) - ซาดี เปพอ - 2021-06-18 - Site
- Plan ID: daf93fb3-a920-474e-9900-1fe3949f0210
- Username: vbdu_5.4.2-1
- App Version: 5.3.25

How to test the 2 scenarios

**Fix for existing downloaded maps**
1. Install [5.3.25](https://github.com/opensrp/opensrp-client-reveal/releases/tag/v5.3.25) apk 
2. Log in, wait for sync to complete and download either 1 or multiple offline maps (do not select either the OA or Plan at this point)
3. After download is complete, turn off access to the internet.
4. Select the OA (operational area) in the hamburger menu and a plan and verify that the map loads 
5. Adjust the time on your device to be 24 or more hours into the future
6. log back in to the device and verify that the ma turns black
7. Upgrade to the latest apk
8. Log back into the app and verify that the map now displays correctly
9. If the map still does not display correctly delete it from the Downloaded maps section
10. Turn on the wifi and download the map again
11. After download is complete turn of the wifi
12. Adjust the time to be 24 or more hours into the future after the download date
11. Log out and back in to the app and verify that the map is displayed correctly

**Fix for newly downloaded maps**
1. Install the latest apk. This is a fresh install
2. Log in, wait for sync to complete and download either 1 or multiple offline maps (do not select either the OA or Plan at this point)
3. After download is complete, turn off access to the internet.
4. Select the OA (operational area) in the hamburger menu and a plan and verify that the map loads 
5. Adjust the time on your device to be 24 or more hours into the future
6. Log back in to the device and verify that the map is displayed correctly

**Comment by ekigamba** [comment]
## Cause

1. Digital globe tiles have a max age of 1 day from the time of downloading. The `cache-control` header also has a `must-revalidate` value
2. Mapbox SDK strictly follows the expiry and `must-revalidate` values and thus does not load expired tiles with a must-revalidate requirement.


## Fix for currently downloaded offlines maps
1. Remove the `must-validate` value for all tiles in this sqlite file `/data/data/org.smartregister.reveal/files/mbgl-offline.db` using the SQLite query `UPDATE tiles SET must_revalidate = 0 WHERE must_revalidate  = 1`


## Permanent fix for new offline map downloads
1. Add an interceptor that rewrites the cache-control header and set it using `HttpRequestUtil.setOkHttpClient(httpClient);`
2. Request Digital globe (Maxar) to remove the `must-validate` cache header. If possible, this can be changed from the developer dashboard
3. Request Mapbox to add an option allowing display of cached/offline tiles with a `must-validate` requirement.

**Comment by madrinekariuki** [comment]
@Rkareko 
I have tested this on both APKs
find below updates specific to each APK.

v5.3.26-rc3
- I downloaded the offline maps (all the maps). 
- noted the maps take a long time to download from (9:00 am - 1:00 pm) internet speed is 5.3mbps
- the maps downloaded.
- switched off the internet.
- selected the OA.
- NOTE when selecting the OA some areas indicate that "Downloading of plans in progress please wait" YET i had downloaded ALL maps.
- I managed to get a plan that was available (for training site 8)
- -maps were visible and i could select the structures
- logged out and changed the device date to after 24 hours.
- logged back in and selected the plan and the maps were still visible and could see the structures.


v.5.3.25
-- I downloaded the offline maps (all the maps). 
- noted the maps take a long time to download .
- the maps downloaded.
- switched off the internet.
- selected the OA.
- NOTE when selecting the OA some areas indicate that "Downloading of plans in progress please wait" YET i had downloaded ALL maps.
- I could not select any plan for this because for all the OAs i keep getting the above message

find screenshots below. showing the message despite having downloaded all the maps.
![image](https://user-images.githubusercontent.com/84722169/126999894-6167069d-f015-4344-a5b8-f9b1fe2f4540.png)
![image](https://user-images.githubusercontent.com/84722169/126999991-d9c8dc9e-9dae-436e-8a10-c8ceaf281256.png)

**Comment by Rkareko** [comment]
@madrinekariuki `Downloading of plans in progress please wait` error is most likely caused by the initial sync not being complete before switching the app to offline mode. This is not related to offline map download

**Comment by madrinekariuki** [comment]
issue related to #1491

**Comment by madrinekariuki** [comment]
tested this using
v5.3.25 preview
v5.3.26 preview
user:test77

findings:
-for v5.3.25 preview the maps are turning black after 24 hours. 
-After upgrading to v5.3.26 preview the maps show correctly even after the 24 hours and one can even open the structures
