### ISSUE TITLE
GPS Point does not move with user

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#209]
GPS point is not moving along with users. Users are requiring to tap the my location button on and off to see the point move.
- Touch My location button to find your current location
- You go to a different place 30 meters (Screen is still on)
- The blue dot is still at the original location.

It appears that the GPS feature isn't refreshing on the screen as implemented in Reveal. It also needs to be updated.

**Comment by githengi** [comment]
This is due to user moving/zooming the map after clicking my location button. 
When a user moves the map after clicking my location button, the my location buttons turns from blue to grey signifying that tracking of user location is turned off.

@craigappl should we still update the user current location after user moves the map

**Comment by craigappl** [comment]
@githengi yes, we should keep the user's location tracking on unless they toggle the my location button again to turn it off. We should snap to the user's current location the first time they toggle the my location button on and then keep updating it regardless of whether the user scrolls or zooms in.
