### ISSUE TITLE
Handle user selecting a new Operational Area in the selector and the Operational area geojson is not yet synced 

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#29]
What happens when a user selects a new Operational Area in the selector and the Operational area geojson is not yet synced should we clear the structures of the previous of the operational area.

If so what will rendered on the map?

This scenario will happen when an Operational Area is defined in OpenMRS Location hierachy but the location object is not  defined on Openrsp server

**Comment by craigappl** [comment]
This could be a good thing because it would allow the user to select an operational area and begin collecting points against it.

There are two scenarios:
1) The operational area is defined, but there are no structures returned
-- Clear the structures of the current operational area
-- The system should still show the white boundary and zoom to it.
-- The system should display a message "There are no structures mapped to this operational area. Please add a point to begin"
2) The operational area is not defined and there are no structures returned
-- Clear the structures of the current operational area
-- The system should display a message "This operational area has not been defined in the system. Please try to sync your device. Please contact the system administrator if that doesn't solve the issue noting the operational area number {OPERATIONAL_AREA_ID}."
-- I think we should still allow users to add points, assuming they know what they are doing (What do you think about this @rowo?)

Note: We should create a reporting in Canopy to identify both of these scenarios.

**Comment by rowo** [comment]
If I understand this correctly — yes sure sounds okay, if we can assume the user will know what they are doing, otherwise they are kind of stuck. If it won't be too much trouble to match up points added by the user and existing structures that weren't synced, that would reduce risk. If it would be difficult or impossible within the context, is there some sort of lite warning message we could have?

**Comment by githengi** [comment]
> -- I think we should still allow users to add points, assuming they know what they are doing (What do you think about this @rowo?)

@craigappl this will break a lot of things since it will be difficult to tag the created structures to an operational area. The structures created would be orphaned

**Comment by craigappl** [comment]
@githengi I agree. We should not allow them to add structures to an operational area that's not defined in the system. I will mark out that statement. Thanks for clarifying. Please close when it's done.
