### ISSUE TITLE
Update core libraries to improve performance

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#311]
These items were added based on the OpenSRP meeting on 15 July:

- [ ] Upgrade core client processor to include support for formatted dates.
- [ ] Performance in CHW app flavors is an issue. Client processes are slow when working offline - it re-processes events offline over and over that aren’t synchronized. Will require DB migrations for everyone.

**Comment by githengi** [comment]
We shall not need to do database migrations since we don't requery events when calling client processor. For both reveal when saving events and clients we invoke the client processor with the events and clients in memory after they are saved so as save unnecessary database query for getting the same data.

We also updated the family module with same functionality as per [https://github.com/OpenSRP/opensrp-client-family/issues/48](https://github.com/OpenSRP/opensrp-client-family/issues/48)

**Comment by githengi** [comment]
Core upgraded to the latest version on Release 2.2.2
