### ISSUE TITLE
RVL-302 Part 2: Support different behaviour in the edit family member form for household head

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#325]
The Thailand team has requested that we change the way the head of household functions in the family module so that the family name reflects the First name of the head of household only. They have requested that we make the following changes in the platform to accommodate this.

If the person being edited is the head of household:
- [x] Remove the checkbox under the surname that says "Surname same as family name"
- [x] Add a checkbox below the firstname of the person that says "First name same as household name"
- [x] If this box is checked, the value that's stored in the client record is the "fam_name" value in the family register form.

If the user edits the family by tapping the option menu and "Registration Info" on the family profile view:
- [x] If the box is checked in the firstname of the head of household, the view updates with the value that's in the fam_name variable in the family view.

**Comment by githengi** [comment]
@craigappl take note that am hiding instead of removing

- [ ] Remove the checkbox under the surname that says "Surname same as family name"


> If the user edits the family by tapping the option menu and "Registration Info" on the family profile view:
The family form opened by tapping "Registration Info" has no checkbox.

Rephrase the above statement

My understanding is that on family head edit form once one checks "First name same as household name" then this value is saved as the new family head first name
