### ISSUE TITLE
Implement the POAT form

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-reveal#332]
- [x] Add a PAOT form in English and Thai [Data dictionary link](https://docs.google.com/spreadsheets/d/1kGPgyF0eJdag19FFL1Oog2gdphdPtKobY4EQ0gMgtgw/edit#gid=227143838&range=B21)

- [x] If the status of the PAOT changes from "Active" to "Inactive" the post save action will make this point inactive in the location and sync the updated location to the server)

- [x] If the status of the PAOT changes from "Active" to "Inactive" the post save action will make this point inactive in the location and sync the updated location to the server

**Comment by githengi** [comment]
@craigappl where are the Thai translations for this form

**Comment by githengi** [comment]
@craigappl Does making the Poat status to Inactive have any effects on how its displayed on map, or actions that can be done on the PAOT

**Comment by craigappl** [comment]
@githengi 
1) I will reach out to the Thai team for translations
2) Yes, if the PAOT is marked as black in the UI because a task was assigned for that PAOT. In the future, no new tasks will be assigned to that PAOT because the location has a status of inactive. If the location is black, users can still tap it to view the card and edit like we do with spray locations.
