### ISSUE TITLE
Investigate why some tasks are not linked to structures

### ISSUE THREAD

**Issue by moshthepitt** [OpenSRP/opensrp-client-reveal#360]
There are reports that some tasks are not linked to structures and thus do not show up in the mobile client.

This is based on the discussion here: https://onaio.slack.com/archives/CBSU8L2SC/p1565055505025300

We should investigate what can cause this and document it and fix it.

**Comment by moshthepitt** [comment]
It would be real nice to have an example task that does not work with the following details:

- the user
- the plan
- the jurisdiction

**Comment by moshthepitt** [comment]
Maybe helpful notes: https://smartregister.atlassian.net/wiki/spaces/REV/pages/1157890049/FI+Planning+Demo+for+Thailand

**Comment by craigappl** [comment]
Note that the issue is in the Android client, not in the reporting solution.

Here's the plan:
https://reveal-stage.smartregister.org/opensrp/rest/plans/5692578d-929a-5620-99e5-e179fa3a2d4f

Here's the jurisdiction:
https://reveal-stage.smartregister.org/opensrp/rest/location/ac7ba751-35e8-4b46-9e53-3cbaad193697?is_jurisdiction=true

Here are the structures on the jurisdiction:
https://reveal-stage.smartregister.org/opensrp/rest/location/sync?parent_id=ac7ba751-35e8-4b46-9e53-3cbaad193697&serverVersion=0

Here's the list of tasks:
https://reveal-stage.smartregister.org/opensrp/rest/task/sync?serverVersion=0&plan=5692578d-929a-5620-99e5-e179fa3a2d4f&group=ac7ba751-35e8-4b46-9e53-3cbaad193697

Here are two sample RACD Register Patient tasks. The first one is the one that was generated within the Reveal Android client and the second one is the one that was created from the Nifi script:
```
{
    "identifier": "6f65cdaf-1387-4e13-acc8-9d576ecc798d",
    "planIdentifier": "5692578d-929a-5620-99e5-e179fa3a2d4f",
    "groupIdentifier": "ac7ba751-35e8-4b46-9e53-3cbaad193697",
    "status": "Ready",
    "businessStatus": "Not Visited",
    "priority": 3,
    "code": "RACD Register Family",
    "description": "Visit the residential structure and register each family member",
    "focus": "RACD Register Family",
    "for": "7d4660b3-576f-4eec-a5a1-62d032356123",
    "executionStartDate": "2019-08-05T1428",
    "executionEndDate": null,
    "authoredOn": "2019-08-05T2328",
    "lastModified": "2019-08-05T2328",
    "owner": "222",
    "note": null,
    "serverVersion": 1565040560677,
    "reasonReference": null
  },
  {
    "identifier": "1e962808-bc4b-48c0-9133-5423f563e721",
    "planIdentifier": "5692578d-929a-5620-99e5-e179fa3a2d4f",
    "groupIdentifier": "ac7ba751-35e8-4b46-9e53-3cbaad193697",
    "status": "Ready",
    "businessStatus": "Not Visited",
    "priority": 3,
    "code": "RACD Register Family",
    "description": "Register all families & family members in all residential structures enumerated (100%) within the operational area",
    "focus": "168fb94d-1889-54cb-bc46-8d06183af881",
    "for": "4d090c30-f8cc-4e95-a710-d836cb076d6d",
    "executionStartDate": "2019-08-05T0000",
    "executionEndDate": "2019-08-12T0000",
    "authoredOn": "2019-08-05T2256",
    "lastModified": "2019-08-05T2358",
    "owner": "nifiUser",
    "note": null,
    "serverVersion": 1565042363403,
    "reasonReference": null
  }
```

**Comment by Rkareko** [comment]
A structure_id field was added to the task table on the client side to simplify queries for retrieving tasks for the tasks register and map view as documented on #241 .

During client processing the _id values from the structure table are used to update the task.structure_id field for a task where the task is attached to a structure i.e. task.for = structure._id .

When displaying structure tasks on the map-view, the task.structure_id is used to determine the tasks that are linked to a structure.

This functionality works when all the structures and the tasks are synced in the same batch (batch size is currently at 1000).

The issue currently occurring is due to the number of tasks surpassing the batch size (approximately 1723 tasks) while the number of structure is within the batch limit i.e approximately 900 structures.

This means task the first 1000 tasks are processed correctly and the task.structure_id value is populated. However the next batch of approximately 723 tasks do not have their task.structure_id populated hence are not displayed on the map view.

The fix is to add an update statement that updates the new batch of tasks (where task.structure_id is null) with a task.structure_id value from the synced structure records where the task.for matches the structure._id .

**Comment by githengi** [comment]
> The fix is to add an update statement that updates the new batch of tasks (where task.structure_id is null) with a task.structure_id value from the synced structure records where the task.for matches the structure._id .

The fix is to add an update statement that updates the new batch of tasks (where task.structure_id is null) with a task.structure_id value from the existing synced structures and family members
