### ISSUE TITLE
Adding Point Form> Out of Operational Area Warning

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#362]
The Namibia implementation isn't going through an enumeration exercise before they deploy field workers for the pilot. Instead, they want to have field workers go through an area and drop points based on their location.

### Problem:
The implementation team is concerned that frontline workers will move to a different operational area in the app without changing the operational area in the hamburger menu. They will train around this, but have requested an intervention within the app to warn the user that they are collecting information outside of the boundaries of the operational area. When you choose the my location button in the add location form, there is no operational area information

They recommended the following solutions:
- Pop up a warning in the add point form if they are going to add a point in a location that's outside the geographic boundary. The user would have to touch a button to get pas the warning
- Add a read only field or banner to the add point form that displays the selected operational area so the user knows which operational area they are in.

I'd like to request @rowo to recommend a solution to this.

**Comment by rowo** [comment]
@craigappl I'm slightly out of the loop.  Is it https://github.com/OpenSRP/opensrp-client-reveal/issues/12#issue-379001143 what has been implemented for the Add Point interaction (with the map and a boundary line)? 

If a user adds a point that isn't in the currently loaded operational area, does it get added to a different OA or to no OA at all?

**Comment by craigappl** [comment]
@rowo, it gets added to the same operational area, but there aren't any visual indicators that the user is actually within the operational area that was selected in the hamburger menu. Currently, it displays the center point with the white border. When a user taps the my location button, it zooms in and it's difficult to figure out which operational area they are in.

They want to implement https://github.com/OpenSRP/opensrp-client-reveal/issues/363 which removes the extra tap on the my location button in the register structure form fragment.

**Comment by rowo** [comment]
@craigappl In the register point form, can the user move their marker on the map (either by dragging or moving 20 feet then retapping "My Location") or does it always add exactly where the GPS initially locates? If the user cannot move their marker after initial load, then showing that dialog on form load seems smart to me. Here's how it might look:

<img src="https://user-images.githubusercontent.com/1584163/62902836-d28b4a80-bd2e-11e9-989d-c97478f06ec1.png" width="300">

If the point is movable after entering the form (and the app knows what area it's in), an in-form notification or warning toaster might be nicer since it would allow a user to finesse where a point is without interacting with this dialog — plus the user wouldn't have to wait until submit to know this information.

I don't understand what showing the currently selected operational area in the form is supposed to do with regards to adding a point inside or outside of the currently selected area. I'm assuming these areas aren't really known on the ground to users or residents, so going to a new village and then seeing the operational area name might not do much. Another option is greying out places under a transparent layer instead of just the operational area outline. Even if you zoom in, it should be obvious that you aren't in the selected area.

<img width="769" alt="Screen Shot 2019-08-12 at 6 34 32 PM" src="https://user-images.githubusercontent.com/1584163/62903226-fa2ee280-bd2f-11e9-9341-7873e2858696.png">

**Comment by Rkareko** [comment]
@craigappl , @githengi from @rowo's comment above, since the marker can be moved after the form has been loaded (correct me if I'm wrong), will we be showing a warning toast message instead of the dialog? 
If this is so what text will the toast display. What happens after the toast message is displayed, i.e. will the app allow the point to be added outside the operational area or prevent this?

**Comment by githengi** [comment]
@Rkareko Its possible to still show the dialog when the marker is moved since we can be able detect when user moves from the map.

**Comment by rowo** [comment]
@githengi I suggested we don't really want that dialog since it can be disruptive depending on how the marker interaction works. @Rkareko what does the user have to do to move the marker? Is it just at any point you can drag and drop the map around? Is there a point where it's clear the user is decided on the marker's location? Is there an APK I can install to look at this?

**Comment by githengi** [comment]
@rowo you can use https://github.com/OpenSRP/opensrp-client-reveal/releases/download/v2.3.3/opensrp-reveal-release-2.3.3-en.apk
There is no point that we can able to decide if user has made a decision to save, this can only be know when they click save. Where the marker is that is where the point is added.
My Suggest is to Implement a validator when they hit save, that displays the Alert Dialog that will then allow to override with the validation when they click continue

**Comment by rowo** [comment]
@githengi I think we can show the dialog when they hit Save definitely and that's probably the minimum MVP functionality.

It would be better UX to also show a little message before that when the point is moved. It's kind of like when filling out a form and you get an error message when filling out a field vs. when you hit submit all the way at the end.

I'm okay with the MVP approach on this for now since it seems adequate. I'm happy to create suggestions for both though.

**Comment by githengi** [comment]
Thanks @rowo you can create suggestions

**Comment by Rkareko** [comment]
@rowo could you provide the color and opacity for the transparent layer used to indicate the area outside the operational area.

**Comment by rowo** [comment]
@Rkareko might need some finessing, but can we try #313131 at 75% opaque?

**Comment by Rkareko** [comment]
@rowo attached is a screenshot of how that looks.
![outside_op_area_313131_mask](https://user-images.githubusercontent.com/47570855/63146242-fdadbc80-c002-11e9-8e65-05a04a8d9327.png)

**Comment by craigappl** [comment]
@rowo and @Rkareko , I recommend that we:
1) Change the opacity so that we can see the underlying area better
2) Make sure that the structure layer is on top of this layer so all structures show up (this may already be the case)

**Comment by rowo** [comment]
@craigappl good call, sounds good. @Rkareko how about 60%?

**Comment by Rkareko** [comment]
@craigappl does the image below address the issues you mentioned satisfactorily ? @rowo, I used 65% opacity, 60% appeared to be a bit too clear when zoomed in.
![split_65_opacity](https://user-images.githubusercontent.com/47570855/63259866-390ced00-c288-11e9-9c1a-294a21a9e18c.png)

**Comment by rowo** [comment]
Ok. Only other solution is to color it some non-Earth color like Cyan so it's even more obvious, but we can see how this works.
