### ISSUE TITLE
RVL-394 Part 1 - Enable Admin Pass in Namibia if my location is deselected on save

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#426]
Users are able to add a location anywhere without a password if the my location is turned off. We need to change the admin password functionality to ask for the password if the my location button is deactivated when the user tries to save the add point form.

**Comment by githengi** [comment]
@craigappl this is the current behavior,
- If my location buttonis disabled, users are still asked for password if they are not within the location buffer of 25 meters
- If location services are not enabled then users are asked to enable it before save so that location can be validated if within the buffer, if not within buffer or users decline to enable location services then password is requested
- If users location cannot be retrieved within 90 seconds by the device using either of GPS/WIFI/Cellular then users are requested for password

I think no further changes are required
