### ISSUE TITLE
Add attribution to Hamburger Menu

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#59]
Discussed on Friday 11 Jan 2019 (@rowo ) please build this in.

**Comment by rowo** [comment]
#### We discussed
- Remove OpenSRP from log in
- Add an attribution section to hamburger menu (that is all OpenSRP)
- Specific language needs refinement. Powered by OpenSRP [v1.0] is the first line. Need to generate ideas for the mSpray and DiSARM lines.

<img width="290" alt="screen shot 2019-01-15 at 9 31 03 am" src="https://user-images.githubusercontent.com/1584163/51186773-68015180-18a8-11e9-9ae0-7d1350f2f1f1.png">

#### Prerequisites
- I think we need to look more at navigation of app that includes navigation for more than one intervention since that may impact the hamburger menu.

**Comment by craigappl** [comment]
@githengi The official attribution should be

Powered by OpenSRP
Built on mSpray and DiSARM

**Comment by craigappl** [comment]
Passed QA
