### ISSUE TITLE
BUG: Spray form text is truncated

### ISSUE THREAD

**Issue by armageddon** [OpenSRP/opensrp-client-reveal#67]
After entering in a value for number of rooms, nets etc, text is truncated

![screenshot_20190117-105821](https://user-images.githubusercontent.com/114864/51307466-70908e00-1a48-11e9-9734-7dea68a88a40.jpg)

**Comment by githengi** [comment]
@rowo kindly advice on how to treat the above forms where the hints are large and cannot fit the screen width.

When no values is entered we are wrapping the hint

![image](https://user-images.githubusercontent.com/25123762/51614263-55d18400-1f36-11e9-8dad-0b9037e74dfa.png)

However after entering a value then the hint is shown at top of material edit text. When an edit text has a value its not possible to wrap the hint 

![image](https://user-images.githubusercontent.com/25123762/51614371-94673e80-1f36-11e9-9ed1-cf46e17f2278.png)

We have two suggestions of how we can resolve this.

**Option 1:**
 Dynamically change the hint whenever a value is input i.e remove the `(Type 99 if unable to assess) ` so that the hint is not truncated

**Option 2:**
We introduce an info icon that has the whole description, and use a short hint e.g. the below screenshots
![image](https://user-images.githubusercontent.com/25123762/51614717-4999f680-1f37-11e9-8855-3a29f92c7bc8.png)

On clicking the info icon then we display the full description/details of that edit text as shown below

![image](https://user-images.githubusercontent.com/25123762/51614797-7948fe80-1f37-11e9-81c0-c091c3f9db0f.png)

**Comment by rowo** [comment]
@githengi I think option 1 is sufficient.

**Comment by craigappl** [comment]
Option 1 passed QA
