### ISSUE TITLE
Add ability to assign teams 

### ISSUE THREAD

**Issue by isabelcshaw** [OpenSRP/opensrp-client-reveal#731]
Like with all IRS plans, the user can assign individual team members to locations in the plan. 

The user will be able to make assignments to the individual distribution point or a "district" in the case that the same team will cover multiple distribution points. 

Mocks from Roger:  
**Note:** _we are not going to implement the map in the top, just the bottom half_
![Assign NTD](https://user-images.githubusercontent.com/12836913/81139468-c6799580-8f1a-11ea-8baa-28c025e0569e.png)

**Comment by cKellyDesign** [comment]
Our current assignment table uses drilldown functionality (vs the nested drawers in the mockup), so it may make sense to keep it drilldown for now given the timelines.

We could also flatten the heirarchy though, so that perhaps we show all schools in a Province (aka ADMIN1) so it's only a single drilldown?

Then I think the only thing will be adding the `Students` column and figuring out how many are at each school.

### API Requirements
- [ ] `GET` a list of all Rosters from an OpenSRP endpoint
- [ ] `GET` a list of all Point Distribution Sites from an OpenSRP endpoint
- [x] `GET` a list of all assignments for the Plan (exists already)
- [x] `POST` a llist of all new/updated assignments for the Plan (exists already)

**Comment by ciremusyoka** [comment]
Assignments are still being done using the existing reveal UI, not the new mockup provided above but with the new functionalities as specified.

**Comment by moshthepitt** [comment]
Fixed by #896
