### ISSUE TITLE
App closes if you login and your session has expired

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#900]
This is a tricky one. The app doesn't crash, it just closes if you login after a long time and your session has expired.

Steps to reproduce:
- Login to the app and sync everything
- Turn off the tablet's screen and wait for 1.5 hours
- Return to the tablet and you should see the login screen again
- Login again and the app closes after you login.
- Open the app again and you're presented with the login screen.

**Comment by githengi** [comment]
I am not able to reproduce after setting up a local server and using shorter access token validity. The app does not crash.

Looking at the [firebase](https://console.firebase.google.com/project/opensrp-production/crashlytics/app/android:org.smartregister.reveal/issues?time=1597276800000:1597967999000&devices=samsung%EF%BF%BFSM-T397U&state=all&type=all) logs on the said dates In think this was being caused by changing the toggle for sync while view is not inflated fully. 

This was fixed by https://github.com/OpenSRP/opensrp-client-reveal/pull/923

**Comment by githengi** [comment]
@craigappl please try to reproduce again

**Comment by craigappl** [comment]
I could not reproduce it on the latest Namibia APK
