### ISSUE TITLE
Download and update user permissions as part of normal sync

### ISSUE THREAD

**Issue by craigappl** [OpenSRP/opensrp-client-reveal#999]
Users in Zambia need to be able to reassign people to different operational areas for the same plan as the team moves around to different districts throughout the spray season. Currently, we only download permissions once the first time a user logs in and we are not able to support moving a team across multiple districts without clearing the app data and downloading everything again. We would like to add support for reassigning users in the web UI and having that reflected the next time the user syncs. It would be fine if we did this when a user logs out and logs in again if that's more appropriate than on every sync.

Acceptance criteria:
- Create a plan IRS that crosses two Rural Health Centres.
- Assign a team to 1 operational area
- Login to the Android app with that user and sync
- Remove that user for that operational area and assign them to another operational area in the web UI
- (optional if required technically) logout of the Android app
- Sync the android app and notice that the operational areas available in the hamburger menu have changed. If an assignment was removed and the user was selected on that operational area, we need to clear the values if they no longer have permission.

**Comment by samkanga** [comment]
[ ] Newly Assigned OA in new HFCA not showing on Hamburger Menu after syn, logout and login.
- I assigned the plan **Dynamic-IRS 2020-09-24_ams** to two health facility catchment areas. 
- I then assigned my team to an operation area under the first catchment area. 
- I logged into the App and was able to select the plan under the assigned area.  
- From the WebUI I changed the assignment to an operational area in the second catchment area
- I synced the app and it gave me the message that I have been logged out due to changes in permissions.
- I logged in again and waited for the app to sync.
- However, I could not see the second operational area listed. The first operational areas that we had deassigned however still showed (there is WIP to resolve this).
- I then cleared data from the app and logged in again.
- This time the second operational area showed up on the hamburger menu

**Comment by samkanga** [comment]
@githengi this now works OK. I am able to see the new OA assigned after the logout and login.
